//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASKI_VACACIONES.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Service_Asky")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VSystem_AskiDataBase", Namespace="http://schemas.datacontract.org/2004/07/Service_Asky")]
    [System.SerializableAttribute()]
    public partial class VSystem_AskiDataBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/Service_Asky.Tables", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASKI_VACACIONES.ServiceReference1.Usuario UsuariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_creacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_ingresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primer_apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primer_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int talento_humanoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASKI_VACACIONES.ServiceReference1.Usuario Usuarios {
            get {
                return this.UsuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuariosField, value) != true)) {
                    this.UsuariosField = value;
                    this.RaisePropertyChanged("Usuarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                if ((this.activoField.Equals(value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_creacion {
            get {
                return this.fecha_creacionField;
            }
            set {
                if ((this.fecha_creacionField.Equals(value) != true)) {
                    this.fecha_creacionField = value;
                    this.RaisePropertyChanged("fecha_creacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_ingreso {
            get {
                return this.fecha_ingresoField;
            }
            set {
                if ((this.fecha_ingresoField.Equals(value) != true)) {
                    this.fecha_ingresoField = value;
                    this.RaisePropertyChanged("fecha_ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primer_apellido {
            get {
                return this.primer_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primer_apellidoField, value) != true)) {
                    this.primer_apellidoField = value;
                    this.RaisePropertyChanged("primer_apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primer_nombre {
            get {
                return this.primer_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.primer_nombreField, value) != true)) {
                    this.primer_nombreField = value;
                    this.RaisePropertyChanged("primer_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundo_apellido {
            get {
                return this.segundo_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_apellidoField, value) != true)) {
                    this.segundo_apellidoField = value;
                    this.RaisePropertyChanged("segundo_apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundo_nombre {
            get {
                return this.segundo_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_nombreField, value) != true)) {
                    this.segundo_nombreField = value;
                    this.RaisePropertyChanged("segundo_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int talento_humano {
            get {
                return this.talento_humanoField;
            }
            set {
                if ((this.talento_humanoField.Equals(value) != true)) {
                    this.talento_humanoField = value;
                    this.RaisePropertyChanged("talento_humano");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ASKI_VACACIONES.ServiceReference1.CompositeType GetDataUsingDataContract(ASKI_VACACIONES.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ASKI_VACACIONES.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getVSystem", ReplyAction="http://tempuri.org/IService1/getVSystemResponse")]
        ASKI_VACACIONES.ServiceReference1.VSystem_AskiDataBase getVSystem(ASKI_VACACIONES.ServiceReference1.VSystem_AskiDataBase vsystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getVSystem", ReplyAction="http://tempuri.org/IService1/getVSystemResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.VSystem_AskiDataBase> getVSystemAsync(ASKI_VACACIONES.ServiceReference1.VSystem_AskiDataBase vsystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addDepartamentos", ReplyAction="http://tempuri.org/IService1/addDepartamentosResponse")]
        void addDepartamentos(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addDepartamentos", ReplyAction="http://tempuri.org/IService1/addDepartamentosResponse")]
        System.Threading.Tasks.Task addDepartamentosAsync(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addRoles", ReplyAction="http://tempuri.org/IService1/addRolesResponse")]
        void addRoles(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addRoles", ReplyAction="http://tempuri.org/IService1/addRolesResponse")]
        System.Threading.Tasks.Task addRolesAsync(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addUsuario", ReplyAction="http://tempuri.org/IService1/addUsuarioResponse")]
        void addUsuario(int talento_humano, string email, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, System.DateTime fecha_ingreso, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addUsuario", ReplyAction="http://tempuri.org/IService1/addUsuarioResponse")]
        System.Threading.Tasks.Task addUsuarioAsync(int talento_humano, string email, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, System.DateTime fecha_ingreso, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addPermisos", ReplyAction="http://tempuri.org/IService1/addPermisosResponse")]
        void addPermisos(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addPermisos", ReplyAction="http://tempuri.org/IService1/addPermisosResponse")]
        System.Threading.Tasks.Task addPermisosAsync(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editPermisos", ReplyAction="http://tempuri.org/IService1/editPermisosResponse")]
        void editPermisos(int id, string descripcion, bool Test);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editPermisos", ReplyAction="http://tempuri.org/IService1/editPermisosResponse")]
        System.Threading.Tasks.Task editPermisosAsync(int id, string descripcion, bool Test);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editRoles", ReplyAction="http://tempuri.org/IService1/editRolesResponse")]
        void editRoles(int id, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editRoles", ReplyAction="http://tempuri.org/IService1/editRolesResponse")]
        System.Threading.Tasks.Task editRolesAsync(int id, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editDepartamentos", ReplyAction="http://tempuri.org/IService1/editDepartamentosResponse")]
        void editDepartamentos(int id, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editDepartamentos", ReplyAction="http://tempuri.org/IService1/editDepartamentosResponse")]
        System.Threading.Tasks.Task editDepartamentosAsync(int id, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletePermisos", ReplyAction="http://tempuri.org/IService1/deletePermisosResponse")]
        void deletePermisos(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletePermisos", ReplyAction="http://tempuri.org/IService1/deletePermisosResponse")]
        System.Threading.Tasks.Task deletePermisosAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/confirmarLogin", ReplyAction="http://tempuri.org/IService1/confirmarLoginResponse")]
        bool confirmarLogin(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/confirmarLogin", ReplyAction="http://tempuri.org/IService1/confirmarLoginResponse")]
        System.Threading.Tasks.Task<bool> confirmarLoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPermisosInfo", ReplyAction="http://tempuri.org/IService1/getPermisosInfoResponse")]
        string getPermisosInfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPermisosInfo", ReplyAction="http://tempuri.org/IService1/getPermisosInfoResponse")]
        System.Threading.Tasks.Task<string> getPermisosInfoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getRolesInfo", ReplyAction="http://tempuri.org/IService1/getRolesInfoResponse")]
        string getRolesInfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getRolesInfo", ReplyAction="http://tempuri.org/IService1/getRolesInfoResponse")]
        System.Threading.Tasks.Task<string> getRolesInfoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDepartamentosInfo", ReplyAction="http://tempuri.org/IService1/getDepartamentosInfoResponse")]
        string getDepartamentosInfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDepartamentosInfo", ReplyAction="http://tempuri.org/IService1/getDepartamentosInfoResponse")]
        System.Threading.Tasks.Task<string> getDepartamentosInfoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsuario", ReplyAction="http://tempuri.org/IService1/getUsuarioResponse")]
        ASKI_VACACIONES.ServiceReference1.Usuario getUsuario(int talento_humano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsuario", ReplyAction="http://tempuri.org/IService1/getUsuarioResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Usuario> getUsuarioAsync(int talento_humano);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ASKI_VACACIONES.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ASKI_VACACIONES.ServiceReference1.IService1>, ASKI_VACACIONES.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ASKI_VACACIONES.ServiceReference1.CompositeType GetDataUsingDataContract(ASKI_VACACIONES.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ASKI_VACACIONES.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ASKI_VACACIONES.ServiceReference1.VSystem_AskiDataBase getVSystem(ASKI_VACACIONES.ServiceReference1.VSystem_AskiDataBase vsystem) {
            return base.Channel.getVSystem(vsystem);
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.VSystem_AskiDataBase> getVSystemAsync(ASKI_VACACIONES.ServiceReference1.VSystem_AskiDataBase vsystem) {
            return base.Channel.getVSystemAsync(vsystem);
        }
        
        public void addDepartamentos(string descripcion) {
            base.Channel.addDepartamentos(descripcion);
        }
        
        public System.Threading.Tasks.Task addDepartamentosAsync(string descripcion) {
            return base.Channel.addDepartamentosAsync(descripcion);
        }
        
        public void addRoles(string descripcion) {
            base.Channel.addRoles(descripcion);
        }
        
        public System.Threading.Tasks.Task addRolesAsync(string descripcion) {
            return base.Channel.addRolesAsync(descripcion);
        }
        
        public void addUsuario(int talento_humano, string email, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, System.DateTime fecha_ingreso, string password) {
            base.Channel.addUsuario(talento_humano, email, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, fecha_ingreso, password);
        }
        
        public System.Threading.Tasks.Task addUsuarioAsync(int talento_humano, string email, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, System.DateTime fecha_ingreso, string password) {
            return base.Channel.addUsuarioAsync(talento_humano, email, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, fecha_ingreso, password);
        }
        
        public void addPermisos(string descripcion) {
            base.Channel.addPermisos(descripcion);
        }
        
        public System.Threading.Tasks.Task addPermisosAsync(string descripcion) {
            return base.Channel.addPermisosAsync(descripcion);
        }
        
        public void editPermisos(int id, string descripcion, bool Test) {
            base.Channel.editPermisos(id, descripcion, Test);
        }
        
        public System.Threading.Tasks.Task editPermisosAsync(int id, string descripcion, bool Test) {
            return base.Channel.editPermisosAsync(id, descripcion, Test);
        }
        
        public void editRoles(int id, string descripcion) {
            base.Channel.editRoles(id, descripcion);
        }
        
        public System.Threading.Tasks.Task editRolesAsync(int id, string descripcion) {
            return base.Channel.editRolesAsync(id, descripcion);
        }
        
        public void editDepartamentos(int id, string descripcion) {
            base.Channel.editDepartamentos(id, descripcion);
        }
        
        public System.Threading.Tasks.Task editDepartamentosAsync(int id, string descripcion) {
            return base.Channel.editDepartamentosAsync(id, descripcion);
        }
        
        public void deletePermisos(int id) {
            base.Channel.deletePermisos(id);
        }
        
        public System.Threading.Tasks.Task deletePermisosAsync(int id) {
            return base.Channel.deletePermisosAsync(id);
        }
        
        public bool confirmarLogin(string email, string password) {
            return base.Channel.confirmarLogin(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> confirmarLoginAsync(string email, string password) {
            return base.Channel.confirmarLoginAsync(email, password);
        }
        
        public string getPermisosInfo(int id) {
            return base.Channel.getPermisosInfo(id);
        }
        
        public System.Threading.Tasks.Task<string> getPermisosInfoAsync(int id) {
            return base.Channel.getPermisosInfoAsync(id);
        }
        
        public string getRolesInfo(int id) {
            return base.Channel.getRolesInfo(id);
        }
        
        public System.Threading.Tasks.Task<string> getRolesInfoAsync(int id) {
            return base.Channel.getRolesInfoAsync(id);
        }
        
        public string getDepartamentosInfo(int id) {
            return base.Channel.getDepartamentosInfo(id);
        }
        
        public System.Threading.Tasks.Task<string> getDepartamentosInfoAsync(int id) {
            return base.Channel.getDepartamentosInfoAsync(id);
        }
        
        public ASKI_VACACIONES.ServiceReference1.Usuario getUsuario(int talento_humano) {
            return base.Channel.getUsuario(talento_humano);
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Usuario> getUsuarioAsync(int talento_humano) {
            return base.Channel.getUsuarioAsync(talento_humano);
        }
    }
}
