//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASKI_VACACIONES.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Service_Asky")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/Service_Asky.Tables")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_creacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_ingresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primer_apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primer_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int talento_humanoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                if ((this.activoField.Equals(value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_creacion {
            get {
                return this.fecha_creacionField;
            }
            set {
                if ((this.fecha_creacionField.Equals(value) != true)) {
                    this.fecha_creacionField = value;
                    this.RaisePropertyChanged("fecha_creacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_ingreso {
            get {
                return this.fecha_ingresoField;
            }
            set {
                if ((this.fecha_ingresoField.Equals(value) != true)) {
                    this.fecha_ingresoField = value;
                    this.RaisePropertyChanged("fecha_ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primer_apellido {
            get {
                return this.primer_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primer_apellidoField, value) != true)) {
                    this.primer_apellidoField = value;
                    this.RaisePropertyChanged("primer_apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primer_nombre {
            get {
                return this.primer_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.primer_nombreField, value) != true)) {
                    this.primer_nombreField = value;
                    this.RaisePropertyChanged("primer_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundo_apellido {
            get {
                return this.segundo_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_apellidoField, value) != true)) {
                    this.segundo_apellidoField = value;
                    this.RaisePropertyChanged("segundo_apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundo_nombre {
            get {
                return this.segundo_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_nombreField, value) != true)) {
                    this.segundo_nombreField = value;
                    this.RaisePropertyChanged("segundo_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int talento_humano {
            get {
                return this.talento_humanoField;
            }
            set {
                if ((this.talento_humanoField.Equals(value) != true)) {
                    this.talento_humanoField = value;
                    this.RaisePropertyChanged("talento_humano");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Permisos", Namespace="http://schemas.datacontract.org/2004/07/Service_Asky.Tables")]
    [System.SerializableAttribute()]
    public partial class Permisos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int permisosidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                if ((this.activoField.Equals(value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int permisosid {
            get {
                return this.permisosidField;
            }
            set {
                if ((this.permisosidField.Equals(value) != true)) {
                    this.permisosidField = value;
                    this.RaisePropertyChanged("permisosid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Roles", Namespace="http://schemas.datacontract.org/2004/07/Service_Asky.Tables")]
    [System.SerializableAttribute()]
    public partial class Roles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rolesidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                if ((this.activoField.Equals(value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rolesid {
            get {
                return this.rolesidField;
            }
            set {
                if ((this.rolesidField.Equals(value) != true)) {
                    this.rolesidField = value;
                    this.RaisePropertyChanged("rolesid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Departamento", Namespace="http://schemas.datacontract.org/2004/07/Service_Asky.Tables")]
    [System.SerializableAttribute()]
    public partial class Departamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int departamentoidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                if ((this.activoField.Equals(value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int departamentoid {
            get {
                return this.departamentoidField;
            }
            set {
                if ((this.departamentoidField.Equals(value) != true)) {
                    this.departamentoidField = value;
                    this.RaisePropertyChanged("departamentoid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Calendario", Namespace="http://schemas.datacontract.org/2004/07/Service_Asky.Tables")]
    [System.SerializableAttribute()]
    public partial class Calendario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int talento_humano_jefeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tipo_dia_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int talento_humano_jefe {
            get {
                return this.talento_humano_jefeField;
            }
            set {
                if ((this.talento_humano_jefeField.Equals(value) != true)) {
                    this.talento_humano_jefeField = value;
                    this.RaisePropertyChanged("talento_humano_jefe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tipo_dia_id {
            get {
                return this.tipo_dia_idField;
            }
            set {
                if ((this.tipo_dia_idField.Equals(value) != true)) {
                    this.tipo_dia_idField = value;
                    this.RaisePropertyChanged("tipo_dia_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jerarquia", Namespace="http://schemas.datacontract.org/2004/07/Service_Asky.Tables")]
    [System.SerializableAttribute()]
    public partial class Jerarquia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int departamentoidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jefe_talentohumanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jerarquiaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int talento_humanoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int departamentoid {
            get {
                return this.departamentoidField;
            }
            set {
                if ((this.departamentoidField.Equals(value) != true)) {
                    this.departamentoidField = value;
                    this.RaisePropertyChanged("departamentoid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jefe_talentohumano {
            get {
                return this.jefe_talentohumanoField;
            }
            set {
                if ((this.jefe_talentohumanoField.Equals(value) != true)) {
                    this.jefe_talentohumanoField = value;
                    this.RaisePropertyChanged("jefe_talentohumano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jerarquiaid {
            get {
                return this.jerarquiaidField;
            }
            set {
                if ((this.jerarquiaidField.Equals(value) != true)) {
                    this.jerarquiaidField = value;
                    this.RaisePropertyChanged("jerarquiaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int talento_humano {
            get {
                return this.talento_humanoField;
            }
            set {
                if ((this.talento_humanoField.Equals(value) != true)) {
                    this.talento_humanoField = value;
                    this.RaisePropertyChanged("talento_humano");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Log_Vacaciones", Namespace="http://schemas.datacontract.org/2004/07/Service_Asky.Tables")]
    [System.SerializableAttribute()]
    public partial class Log_Vacaciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estatus_actualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> estatus_anteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_modificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int logidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int th_modificoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int vacacionesidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estatus_actual {
            get {
                return this.estatus_actualField;
            }
            set {
                if ((this.estatus_actualField.Equals(value) != true)) {
                    this.estatus_actualField = value;
                    this.RaisePropertyChanged("estatus_actual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> estatus_anterior {
            get {
                return this.estatus_anteriorField;
            }
            set {
                if ((this.estatus_anteriorField.Equals(value) != true)) {
                    this.estatus_anteriorField = value;
                    this.RaisePropertyChanged("estatus_anterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_modificacion {
            get {
                return this.fecha_modificacionField;
            }
            set {
                if ((this.fecha_modificacionField.Equals(value) != true)) {
                    this.fecha_modificacionField = value;
                    this.RaisePropertyChanged("fecha_modificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int logid {
            get {
                return this.logidField;
            }
            set {
                if ((this.logidField.Equals(value) != true)) {
                    this.logidField = value;
                    this.RaisePropertyChanged("logid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int th_modifico {
            get {
                return this.th_modificoField;
            }
            set {
                if ((this.th_modificoField.Equals(value) != true)) {
                    this.th_modificoField = value;
                    this.RaisePropertyChanged("th_modifico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int vacacionesid {
            get {
                return this.vacacionesidField;
            }
            set {
                if ((this.vacacionesidField.Equals(value) != true)) {
                    this.vacacionesidField = value;
                    this.RaisePropertyChanged("vacacionesid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/Service_Asky.Tables")]
    [System.SerializableAttribute()]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estatusidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                if ((this.activoField.Equals(value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estatusid {
            get {
                return this.estatusidField;
            }
            set {
                if ((this.estatusidField.Equals(value) != true)) {
                    this.estatusidField = value;
                    this.RaisePropertyChanged("estatusid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tipo_Dia", Namespace="http://schemas.datacontract.org/2004/07/Service_Asky.Tables")]
    [System.SerializableAttribute()]
    public partial class Tipo_Dia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tipo_dia_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tipo_dia_id {
            get {
                return this.tipo_dia_idField;
            }
            set {
                if ((this.tipo_dia_idField.Equals(value) != true)) {
                    this.tipo_dia_idField = value;
                    this.RaisePropertyChanged("tipo_dia_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vacaciones", Namespace="http://schemas.datacontract.org/2004/07/Service_Asky.Tables")]
    [System.SerializableAttribute()]
    public partial class Vacaciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int dias_solicitadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estatusidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_de_aprobacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_entradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_salidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_solicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int talento_humanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int vacacionesidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int dias_solicitados {
            get {
                return this.dias_solicitadosField;
            }
            set {
                if ((this.dias_solicitadosField.Equals(value) != true)) {
                    this.dias_solicitadosField = value;
                    this.RaisePropertyChanged("dias_solicitados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estatusid {
            get {
                return this.estatusidField;
            }
            set {
                if ((this.estatusidField.Equals(value) != true)) {
                    this.estatusidField = value;
                    this.RaisePropertyChanged("estatusid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_de_aprobacion {
            get {
                return this.fecha_de_aprobacionField;
            }
            set {
                if ((this.fecha_de_aprobacionField.Equals(value) != true)) {
                    this.fecha_de_aprobacionField = value;
                    this.RaisePropertyChanged("fecha_de_aprobacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_entrada {
            get {
                return this.fecha_entradaField;
            }
            set {
                if ((this.fecha_entradaField.Equals(value) != true)) {
                    this.fecha_entradaField = value;
                    this.RaisePropertyChanged("fecha_entrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_salida {
            get {
                return this.fecha_salidaField;
            }
            set {
                if ((this.fecha_salidaField.Equals(value) != true)) {
                    this.fecha_salidaField = value;
                    this.RaisePropertyChanged("fecha_salida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_solicitud {
            get {
                return this.fecha_solicitudField;
            }
            set {
                if ((this.fecha_solicitudField.Equals(value) != true)) {
                    this.fecha_solicitudField = value;
                    this.RaisePropertyChanged("fecha_solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int talento_humano {
            get {
                return this.talento_humanoField;
            }
            set {
                if ((this.talento_humanoField.Equals(value) != true)) {
                    this.talento_humanoField = value;
                    this.RaisePropertyChanged("talento_humano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int vacacionesid {
            get {
                return this.vacacionesidField;
            }
            set {
                if ((this.vacacionesidField.Equals(value) != true)) {
                    this.vacacionesidField = value;
                    this.RaisePropertyChanged("vacacionesid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int year {
            get {
                return this.yearField;
            }
            set {
                if ((this.yearField.Equals(value) != true)) {
                    this.yearField = value;
                    this.RaisePropertyChanged("year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ASKI_VACACIONES.ServiceReference1.CompositeType GetDataUsingDataContract(ASKI_VACACIONES.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ASKI_VACACIONES.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addDepartamento", ReplyAction="http://tempuri.org/IService1/addDepartamentoResponse")]
        void addDepartamento(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addDepartamento", ReplyAction="http://tempuri.org/IService1/addDepartamentoResponse")]
        System.Threading.Tasks.Task addDepartamentoAsync(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addRole", ReplyAction="http://tempuri.org/IService1/addRoleResponse")]
        void addRole(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addRole", ReplyAction="http://tempuri.org/IService1/addRoleResponse")]
        System.Threading.Tasks.Task addRoleAsync(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addUsuario", ReplyAction="http://tempuri.org/IService1/addUsuarioResponse")]
        void addUsuario(int talento_humano, string email, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, System.DateTime fecha_ingreso, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addUsuario", ReplyAction="http://tempuri.org/IService1/addUsuarioResponse")]
        System.Threading.Tasks.Task addUsuarioAsync(int talento_humano, string email, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, System.DateTime fecha_ingreso, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addPermiso", ReplyAction="http://tempuri.org/IService1/addPermisoResponse")]
        void addPermiso(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addPermiso", ReplyAction="http://tempuri.org/IService1/addPermisoResponse")]
        System.Threading.Tasks.Task addPermisoAsync(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addUsuario_Departamento", ReplyAction="http://tempuri.org/IService1/addUsuario_DepartamentoResponse")]
        void addUsuario_Departamento(int talentoHumano, int idDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addUsuario_Departamento", ReplyAction="http://tempuri.org/IService1/addUsuario_DepartamentoResponse")]
        System.Threading.Tasks.Task addUsuario_DepartamentoAsync(int talentoHumano, int idDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addUsuario_Rol", ReplyAction="http://tempuri.org/IService1/addUsuario_RolResponse")]
        void addUsuario_Rol(int talentoHumano, int idRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addUsuario_Rol", ReplyAction="http://tempuri.org/IService1/addUsuario_RolResponse")]
        System.Threading.Tasks.Task addUsuario_RolAsync(int talentoHumano, int idRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addRoles_Permisos", ReplyAction="http://tempuri.org/IService1/addRoles_PermisosResponse")]
        void addRoles_Permisos(int idRol, int idPermiso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addRoles_Permisos", ReplyAction="http://tempuri.org/IService1/addRoles_PermisosResponse")]
        System.Threading.Tasks.Task addRoles_PermisosAsync(int idRol, int idPermiso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addDepartamento_Jefe", ReplyAction="http://tempuri.org/IService1/addDepartamento_JefeResponse")]
        void addDepartamento_Jefe(int talentoHumano, int idDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addDepartamento_Jefe", ReplyAction="http://tempuri.org/IService1/addDepartamento_JefeResponse")]
        System.Threading.Tasks.Task addDepartamento_JefeAsync(int talentoHumano, int idDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addJerarquia", ReplyAction="http://tempuri.org/IService1/addJerarquiaResponse")]
        void addJerarquia(int talento_humano, int talento_humano_Jefe, int departamentoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addJerarquia", ReplyAction="http://tempuri.org/IService1/addJerarquiaResponse")]
        System.Threading.Tasks.Task addJerarquiaAsync(int talento_humano, int talento_humano_Jefe, int departamentoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addTipo_dia", ReplyAction="http://tempuri.org/IService1/addTipo_diaResponse")]
        void addTipo_dia(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addTipo_dia", ReplyAction="http://tempuri.org/IService1/addTipo_diaResponse")]
        System.Threading.Tasks.Task addTipo_diaAsync(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addCalendario", ReplyAction="http://tempuri.org/IService1/addCalendarioResponse")]
        void addCalendario(int talento_humano_jefe, string fecha, int tipo_dia_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addCalendario", ReplyAction="http://tempuri.org/IService1/addCalendarioResponse")]
        System.Threading.Tasks.Task addCalendarioAsync(int talento_humano_jefe, string fecha, int tipo_dia_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addVacacion", ReplyAction="http://tempuri.org/IService1/addVacacionResponse")]
        void addVacacion(int talentoHumano, int year, System.DateTime fechaSalida, System.DateTime fechaEntrada, System.DateTime fechaSolicitud, System.DateTime fechaAprobacion, int statusid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addVacacion", ReplyAction="http://tempuri.org/IService1/addVacacionResponse")]
        System.Threading.Tasks.Task addVacacionAsync(int talentoHumano, int year, System.DateTime fechaSalida, System.DateTime fechaEntrada, System.DateTime fechaSolicitud, System.DateTime fechaAprobacion, int statusid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addLogVacaciones", ReplyAction="http://tempuri.org/IService1/addLogVacacionesResponse")]
        void addLogVacaciones(int vacacionesid, int talentoHumano_Modifico, int estatusAnterior, int estatusActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addLogVacaciones", ReplyAction="http://tempuri.org/IService1/addLogVacacionesResponse")]
        System.Threading.Tasks.Task addLogVacacionesAsync(int vacacionesid, int talentoHumano_Modifico, int estatusAnterior, int estatusActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/approveRequest", ReplyAction="http://tempuri.org/IService1/approveRequestResponse")]
        bool approveRequest(System.DateTime fechaSalida, System.DateTime fechaEntrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/approveRequest", ReplyAction="http://tempuri.org/IService1/approveRequestResponse")]
        System.Threading.Tasks.Task<bool> approveRequestAsync(System.DateTime fechaSalida, System.DateTime fechaEntrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editPermiso", ReplyAction="http://tempuri.org/IService1/editPermisoResponse")]
        void editPermiso(int id, string descripcion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editPermiso", ReplyAction="http://tempuri.org/IService1/editPermisoResponse")]
        System.Threading.Tasks.Task editPermisoAsync(int id, string descripcion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editRol", ReplyAction="http://tempuri.org/IService1/editRolResponse")]
        void editRol(int id, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editRol", ReplyAction="http://tempuri.org/IService1/editRolResponse")]
        System.Threading.Tasks.Task editRolAsync(int id, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editDepartamento", ReplyAction="http://tempuri.org/IService1/editDepartamentoResponse")]
        void editDepartamento(int id, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editDepartamento", ReplyAction="http://tempuri.org/IService1/editDepartamentoResponse")]
        System.Threading.Tasks.Task editDepartamentoAsync(int id, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editUsuario", ReplyAction="http://tempuri.org/IService1/editUsuarioResponse")]
        void editUsuario(int talentoHumano, string email, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, System.DateTime fechaIngreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editUsuario", ReplyAction="http://tempuri.org/IService1/editUsuarioResponse")]
        System.Threading.Tasks.Task editUsuarioAsync(int talentoHumano, string email, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, System.DateTime fechaIngreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/perfil", ReplyAction="http://tempuri.org/IService1/perfilResponse")]
        void perfil(int talentohumano, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/perfil", ReplyAction="http://tempuri.org/IService1/perfilResponse")]
        System.Threading.Tasks.Task perfilAsync(int talentohumano, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletePermiso", ReplyAction="http://tempuri.org/IService1/deletePermisoResponse")]
        void deletePermiso(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletePermiso", ReplyAction="http://tempuri.org/IService1/deletePermisoResponse")]
        System.Threading.Tasks.Task deletePermisoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteRoles_Usuarios", ReplyAction="http://tempuri.org/IService1/deleteRoles_UsuariosResponse")]
        void deleteRoles_Usuarios(int talentoHumano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteRoles_Usuarios", ReplyAction="http://tempuri.org/IService1/deleteRoles_UsuariosResponse")]
        System.Threading.Tasks.Task deleteRoles_UsuariosAsync(int talentoHumano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteDepartamento_Usuarios", ReplyAction="http://tempuri.org/IService1/deleteDepartamento_UsuariosResponse")]
        void deleteDepartamento_Usuarios(int talentoHumano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteDepartamento_Usuarios", ReplyAction="http://tempuri.org/IService1/deleteDepartamento_UsuariosResponse")]
        System.Threading.Tasks.Task deleteDepartamento_UsuariosAsync(int talentoHumano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteDepartamento_Jefe", ReplyAction="http://tempuri.org/IService1/deleteDepartamento_JefeResponse")]
        void deleteDepartamento_Jefe(int talentoHumano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteDepartamento_Jefe", ReplyAction="http://tempuri.org/IService1/deleteDepartamento_JefeResponse")]
        System.Threading.Tasks.Task deleteDepartamento_JefeAsync(int talentoHumano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/confirmarLogin", ReplyAction="http://tempuri.org/IService1/confirmarLoginResponse")]
        ASKI_VACACIONES.ServiceReference1.Usuario confirmarLogin(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/confirmarLogin", ReplyAction="http://tempuri.org/IService1/confirmarLoginResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Usuario> confirmarLoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPermiso", ReplyAction="http://tempuri.org/IService1/getPermisoResponse")]
        ASKI_VACACIONES.ServiceReference1.Permisos getPermiso(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPermiso", ReplyAction="http://tempuri.org/IService1/getPermisoResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Permisos> getPermisoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getRol", ReplyAction="http://tempuri.org/IService1/getRolResponse")]
        ASKI_VACACIONES.ServiceReference1.Roles getRol(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getRol", ReplyAction="http://tempuri.org/IService1/getRolResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Roles> getRolAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDepartamento", ReplyAction="http://tempuri.org/IService1/getDepartamentoResponse")]
        ASKI_VACACIONES.ServiceReference1.Departamento getDepartamento(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDepartamento", ReplyAction="http://tempuri.org/IService1/getDepartamentoResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Departamento> getDepartamentoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsuario", ReplyAction="http://tempuri.org/IService1/getUsuarioResponse")]
        ASKI_VACACIONES.ServiceReference1.Usuario getUsuario(int talento_humano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsuario", ReplyAction="http://tempuri.org/IService1/getUsuarioResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Usuario> getUsuarioAsync(int talento_humano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_calendario", ReplyAction="http://tempuri.org/IService1/getTbl_calendarioResponse")]
        ASKI_VACACIONES.ServiceReference1.Calendario[] getTbl_calendario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_calendario", ReplyAction="http://tempuri.org/IService1/getTbl_calendarioResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Calendario[]> getTbl_calendarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_departamentos", ReplyAction="http://tempuri.org/IService1/getTbl_departamentosResponse")]
        ASKI_VACACIONES.ServiceReference1.Departamento[] getTbl_departamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_departamentos", ReplyAction="http://tempuri.org/IService1/getTbl_departamentosResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Departamento[]> getTbl_departamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_jerarquia", ReplyAction="http://tempuri.org/IService1/getTbl_jerarquiaResponse")]
        ASKI_VACACIONES.ServiceReference1.Jerarquia[] getTbl_jerarquia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_jerarquia", ReplyAction="http://tempuri.org/IService1/getTbl_jerarquiaResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Jerarquia[]> getTbl_jerarquiaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_log_vacaciones", ReplyAction="http://tempuri.org/IService1/getTbl_log_vacacionesResponse")]
        ASKI_VACACIONES.ServiceReference1.Log_Vacaciones[] getTbl_log_vacaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_log_vacaciones", ReplyAction="http://tempuri.org/IService1/getTbl_log_vacacionesResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Log_Vacaciones[]> getTbl_log_vacacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_permisos", ReplyAction="http://tempuri.org/IService1/getTbl_permisosResponse")]
        ASKI_VACACIONES.ServiceReference1.Permisos[] getTbl_permisos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_permisos", ReplyAction="http://tempuri.org/IService1/getTbl_permisosResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Permisos[]> getTbl_permisosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_roles", ReplyAction="http://tempuri.org/IService1/getTbl_rolesResponse")]
        ASKI_VACACIONES.ServiceReference1.Roles[] getTbl_roles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_roles", ReplyAction="http://tempuri.org/IService1/getTbl_rolesResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Roles[]> getTbl_rolesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_status", ReplyAction="http://tempuri.org/IService1/getTbl_statusResponse")]
        ASKI_VACACIONES.ServiceReference1.Status[] getTbl_status();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_status", ReplyAction="http://tempuri.org/IService1/getTbl_statusResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Status[]> getTbl_statusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_tipo_dia", ReplyAction="http://tempuri.org/IService1/getTbl_tipo_diaResponse")]
        ASKI_VACACIONES.ServiceReference1.Tipo_Dia[] getTbl_tipo_dia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_tipo_dia", ReplyAction="http://tempuri.org/IService1/getTbl_tipo_diaResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Tipo_Dia[]> getTbl_tipo_diaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_usuarios", ReplyAction="http://tempuri.org/IService1/getTbl_usuariosResponse")]
        ASKI_VACACIONES.ServiceReference1.Usuario[] getTbl_usuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_usuarios", ReplyAction="http://tempuri.org/IService1/getTbl_usuariosResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Usuario[]> getTbl_usuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_vacaciones", ReplyAction="http://tempuri.org/IService1/getTbl_vacacionesResponse")]
        ASKI_VACACIONES.ServiceReference1.Vacaciones[] getTbl_vacaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTbl_vacaciones", ReplyAction="http://tempuri.org/IService1/getTbl_vacacionesResponse")]
        System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Vacaciones[]> getTbl_vacacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUltimoId_Roles", ReplyAction="http://tempuri.org/IService1/getUltimoId_RolesResponse")]
        int getUltimoId_Roles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUltimoId_Roles", ReplyAction="http://tempuri.org/IService1/getUltimoId_RolesResponse")]
        System.Threading.Tasks.Task<int> getUltimoId_RolesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getLista_Permisos", ReplyAction="http://tempuri.org/IService1/getLista_PermisosResponse")]
        string[] getLista_Permisos(int talento_humano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getLista_Permisos", ReplyAction="http://tempuri.org/IService1/getLista_PermisosResponse")]
        System.Threading.Tasks.Task<string[]> getLista_PermisosAsync(int talento_humano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getIdsRoles_Usuario", ReplyAction="http://tempuri.org/IService1/getIdsRoles_UsuarioResponse")]
        string[] getIdsRoles_Usuario(int talentoHumano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getIdsRoles_Usuario", ReplyAction="http://tempuri.org/IService1/getIdsRoles_UsuarioResponse")]
        System.Threading.Tasks.Task<string[]> getIdsRoles_UsuarioAsync(int talentoHumano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getIdDepartamentos_Usuario", ReplyAction="http://tempuri.org/IService1/getIdDepartamentos_UsuarioResponse")]
        string[] getIdDepartamentos_Usuario(int talentoHumano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getIdDepartamentos_Usuario", ReplyAction="http://tempuri.org/IService1/getIdDepartamentos_UsuarioResponse")]
        System.Threading.Tasks.Task<string[]> getIdDepartamentos_UsuarioAsync(int talentoHumano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_fecha", ReplyAction="http://tempuri.org/IService1/get_fechaResponse")]
        string[] get_fecha(int tipo_dia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_fecha", ReplyAction="http://tempuri.org/IService1/get_fechaResponse")]
        System.Threading.Tasks.Task<string[]> get_fechaAsync(int tipo_dia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getultimoid_tipodia", ReplyAction="http://tempuri.org/IService1/getultimoid_tipodiaResponse")]
        int getultimoid_tipodia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getultimoid_tipodia", ReplyAction="http://tempuri.org/IService1/getultimoid_tipodiaResponse")]
        System.Threading.Tasks.Task<int> getultimoid_tipodiaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_eventos", ReplyAction="http://tempuri.org/IService1/get_eventosResponse")]
        string[] get_eventos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_eventos", ReplyAction="http://tempuri.org/IService1/get_eventosResponse")]
        System.Threading.Tasks.Task<string[]> get_eventosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_fecha_eventos", ReplyAction="http://tempuri.org/IService1/get_fecha_eventosResponse")]
        string[] get_fecha_eventos(string evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_fecha_eventos", ReplyAction="http://tempuri.org/IService1/get_fecha_eventosResponse")]
        System.Threading.Tasks.Task<string[]> get_fecha_eventosAsync(string evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDepartamento_Usuario", ReplyAction="http://tempuri.org/IService1/getDepartamento_UsuarioResponse")]
        string[][] getDepartamento_Usuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDepartamento_Usuario", ReplyAction="http://tempuri.org/IService1/getDepartamento_UsuarioResponse")]
        System.Threading.Tasks.Task<string[][]> getDepartamento_UsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getJefe_Departamento", ReplyAction="http://tempuri.org/IService1/getJefe_DepartamentoResponse")]
        string getJefe_Departamento(int departamentoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getJefe_Departamento", ReplyAction="http://tempuri.org/IService1/getJefe_DepartamentoResponse")]
        System.Threading.Tasks.Task<string> getJefe_DepartamentoAsync(int departamentoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTalentoHumano_Jefe_Departamento", ReplyAction="http://tempuri.org/IService1/getTalentoHumano_Jefe_DepartamentoResponse")]
        int getTalentoHumano_Jefe_Departamento(int departamentoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTalentoHumano_Jefe_Departamento", ReplyAction="http://tempuri.org/IService1/getTalentoHumano_Jefe_DepartamentoResponse")]
        System.Threading.Tasks.Task<int> getTalentoHumano_Jefe_DepartamentoAsync(int departamentoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTalentoHumano_Jefe", ReplyAction="http://tempuri.org/IService1/getTalentoHumano_JefeResponse")]
        int getTalentoHumano_Jefe(int talentoHumano_empleado, int departamentoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTalentoHumano_Jefe", ReplyAction="http://tempuri.org/IService1/getTalentoHumano_JefeResponse")]
        System.Threading.Tasks.Task<int> getTalentoHumano_JefeAsync(int talentoHumano_empleado, int departamentoid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ASKI_VACACIONES.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ASKI_VACACIONES.ServiceReference1.IService1>, ASKI_VACACIONES.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ASKI_VACACIONES.ServiceReference1.CompositeType GetDataUsingDataContract(ASKI_VACACIONES.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ASKI_VACACIONES.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public void addDepartamento(string descripcion) {
            base.Channel.addDepartamento(descripcion);
        }
        
        public System.Threading.Tasks.Task addDepartamentoAsync(string descripcion) {
            return base.Channel.addDepartamentoAsync(descripcion);
        }
        
        public void addRole(string descripcion) {
            base.Channel.addRole(descripcion);
        }
        
        public System.Threading.Tasks.Task addRoleAsync(string descripcion) {
            return base.Channel.addRoleAsync(descripcion);
        }
        
        public void addUsuario(int talento_humano, string email, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, System.DateTime fecha_ingreso, string password) {
            base.Channel.addUsuario(talento_humano, email, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, fecha_ingreso, password);
        }
        
        public System.Threading.Tasks.Task addUsuarioAsync(int talento_humano, string email, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, System.DateTime fecha_ingreso, string password) {
            return base.Channel.addUsuarioAsync(talento_humano, email, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, fecha_ingreso, password);
        }
        
        public void addPermiso(string descripcion) {
            base.Channel.addPermiso(descripcion);
        }
        
        public System.Threading.Tasks.Task addPermisoAsync(string descripcion) {
            return base.Channel.addPermisoAsync(descripcion);
        }
        
        public void addUsuario_Departamento(int talentoHumano, int idDepartamento) {
            base.Channel.addUsuario_Departamento(talentoHumano, idDepartamento);
        }
        
        public System.Threading.Tasks.Task addUsuario_DepartamentoAsync(int talentoHumano, int idDepartamento) {
            return base.Channel.addUsuario_DepartamentoAsync(talentoHumano, idDepartamento);
        }
        
        public void addUsuario_Rol(int talentoHumano, int idRol) {
            base.Channel.addUsuario_Rol(talentoHumano, idRol);
        }
        
        public System.Threading.Tasks.Task addUsuario_RolAsync(int talentoHumano, int idRol) {
            return base.Channel.addUsuario_RolAsync(talentoHumano, idRol);
        }
        
        public void addRoles_Permisos(int idRol, int idPermiso) {
            base.Channel.addRoles_Permisos(idRol, idPermiso);
        }
        
        public System.Threading.Tasks.Task addRoles_PermisosAsync(int idRol, int idPermiso) {
            return base.Channel.addRoles_PermisosAsync(idRol, idPermiso);
        }
        
        public void addDepartamento_Jefe(int talentoHumano, int idDepartamento) {
            base.Channel.addDepartamento_Jefe(talentoHumano, idDepartamento);
        }
        
        public System.Threading.Tasks.Task addDepartamento_JefeAsync(int talentoHumano, int idDepartamento) {
            return base.Channel.addDepartamento_JefeAsync(talentoHumano, idDepartamento);
        }
        
        public void addJerarquia(int talento_humano, int talento_humano_Jefe, int departamentoid) {
            base.Channel.addJerarquia(talento_humano, talento_humano_Jefe, departamentoid);
        }
        
        public System.Threading.Tasks.Task addJerarquiaAsync(int talento_humano, int talento_humano_Jefe, int departamentoid) {
            return base.Channel.addJerarquiaAsync(talento_humano, talento_humano_Jefe, departamentoid);
        }
        
        public void addTipo_dia(string descripcion) {
            base.Channel.addTipo_dia(descripcion);
        }
        
        public System.Threading.Tasks.Task addTipo_diaAsync(string descripcion) {
            return base.Channel.addTipo_diaAsync(descripcion);
        }
        
        public void addCalendario(int talento_humano_jefe, string fecha, int tipo_dia_id) {
            base.Channel.addCalendario(talento_humano_jefe, fecha, tipo_dia_id);
        }
        
        public System.Threading.Tasks.Task addCalendarioAsync(int talento_humano_jefe, string fecha, int tipo_dia_id) {
            return base.Channel.addCalendarioAsync(talento_humano_jefe, fecha, tipo_dia_id);
        }
        
        public void addVacacion(int talentoHumano, int year, System.DateTime fechaSalida, System.DateTime fechaEntrada, System.DateTime fechaSolicitud, System.DateTime fechaAprobacion, int statusid) {
            base.Channel.addVacacion(talentoHumano, year, fechaSalida, fechaEntrada, fechaSolicitud, fechaAprobacion, statusid);
        }
        
        public System.Threading.Tasks.Task addVacacionAsync(int talentoHumano, int year, System.DateTime fechaSalida, System.DateTime fechaEntrada, System.DateTime fechaSolicitud, System.DateTime fechaAprobacion, int statusid) {
            return base.Channel.addVacacionAsync(talentoHumano, year, fechaSalida, fechaEntrada, fechaSolicitud, fechaAprobacion, statusid);
        }
        
        public void addLogVacaciones(int vacacionesid, int talentoHumano_Modifico, int estatusAnterior, int estatusActual) {
            base.Channel.addLogVacaciones(vacacionesid, talentoHumano_Modifico, estatusAnterior, estatusActual);
        }
        
        public System.Threading.Tasks.Task addLogVacacionesAsync(int vacacionesid, int talentoHumano_Modifico, int estatusAnterior, int estatusActual) {
            return base.Channel.addLogVacacionesAsync(vacacionesid, talentoHumano_Modifico, estatusAnterior, estatusActual);
        }
        
        public bool approveRequest(System.DateTime fechaSalida, System.DateTime fechaEntrada) {
            return base.Channel.approveRequest(fechaSalida, fechaEntrada);
        }
        
        public System.Threading.Tasks.Task<bool> approveRequestAsync(System.DateTime fechaSalida, System.DateTime fechaEntrada) {
            return base.Channel.approveRequestAsync(fechaSalida, fechaEntrada);
        }
        
        public void editPermiso(int id, string descripcion, bool activo) {
            base.Channel.editPermiso(id, descripcion, activo);
        }
        
        public System.Threading.Tasks.Task editPermisoAsync(int id, string descripcion, bool activo) {
            return base.Channel.editPermisoAsync(id, descripcion, activo);
        }
        
        public void editRol(int id, string descripcion) {
            base.Channel.editRol(id, descripcion);
        }
        
        public System.Threading.Tasks.Task editRolAsync(int id, string descripcion) {
            return base.Channel.editRolAsync(id, descripcion);
        }
        
        public void editDepartamento(int id, string descripcion) {
            base.Channel.editDepartamento(id, descripcion);
        }
        
        public System.Threading.Tasks.Task editDepartamentoAsync(int id, string descripcion) {
            return base.Channel.editDepartamentoAsync(id, descripcion);
        }
        
        public void editUsuario(int talentoHumano, string email, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, System.DateTime fechaIngreso) {
            base.Channel.editUsuario(talentoHumano, email, primerNombre, segundoNombre, primerApellido, segundoApellido, fechaIngreso);
        }
        
        public System.Threading.Tasks.Task editUsuarioAsync(int talentoHumano, string email, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, System.DateTime fechaIngreso) {
            return base.Channel.editUsuarioAsync(talentoHumano, email, primerNombre, segundoNombre, primerApellido, segundoApellido, fechaIngreso);
        }
        
        public void perfil(int talentohumano, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, string correo) {
            base.Channel.perfil(talentohumano, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, correo);
        }
        
        public System.Threading.Tasks.Task perfilAsync(int talentohumano, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, string correo) {
            return base.Channel.perfilAsync(talentohumano, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, correo);
        }
        
        public void deletePermiso(int id) {
            base.Channel.deletePermiso(id);
        }
        
        public System.Threading.Tasks.Task deletePermisoAsync(int id) {
            return base.Channel.deletePermisoAsync(id);
        }
        
        public void deleteRoles_Usuarios(int talentoHumano) {
            base.Channel.deleteRoles_Usuarios(talentoHumano);
        }
        
        public System.Threading.Tasks.Task deleteRoles_UsuariosAsync(int talentoHumano) {
            return base.Channel.deleteRoles_UsuariosAsync(talentoHumano);
        }
        
        public void deleteDepartamento_Usuarios(int talentoHumano) {
            base.Channel.deleteDepartamento_Usuarios(talentoHumano);
        }
        
        public System.Threading.Tasks.Task deleteDepartamento_UsuariosAsync(int talentoHumano) {
            return base.Channel.deleteDepartamento_UsuariosAsync(talentoHumano);
        }
        
        public void deleteDepartamento_Jefe(int talentoHumano) {
            base.Channel.deleteDepartamento_Jefe(talentoHumano);
        }
        
        public System.Threading.Tasks.Task deleteDepartamento_JefeAsync(int talentoHumano) {
            return base.Channel.deleteDepartamento_JefeAsync(talentoHumano);
        }
        
        public ASKI_VACACIONES.ServiceReference1.Usuario confirmarLogin(string email, string password) {
            return base.Channel.confirmarLogin(email, password);
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Usuario> confirmarLoginAsync(string email, string password) {
            return base.Channel.confirmarLoginAsync(email, password);
        }
        
        public ASKI_VACACIONES.ServiceReference1.Permisos getPermiso(int id) {
            return base.Channel.getPermiso(id);
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Permisos> getPermisoAsync(int id) {
            return base.Channel.getPermisoAsync(id);
        }
        
        public ASKI_VACACIONES.ServiceReference1.Roles getRol(int id) {
            return base.Channel.getRol(id);
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Roles> getRolAsync(int id) {
            return base.Channel.getRolAsync(id);
        }
        
        public ASKI_VACACIONES.ServiceReference1.Departamento getDepartamento(int id) {
            return base.Channel.getDepartamento(id);
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Departamento> getDepartamentoAsync(int id) {
            return base.Channel.getDepartamentoAsync(id);
        }
        
        public ASKI_VACACIONES.ServiceReference1.Usuario getUsuario(int talento_humano) {
            return base.Channel.getUsuario(talento_humano);
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Usuario> getUsuarioAsync(int talento_humano) {
            return base.Channel.getUsuarioAsync(talento_humano);
        }
        
        public ASKI_VACACIONES.ServiceReference1.Calendario[] getTbl_calendario() {
            return base.Channel.getTbl_calendario();
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Calendario[]> getTbl_calendarioAsync() {
            return base.Channel.getTbl_calendarioAsync();
        }
        
        public ASKI_VACACIONES.ServiceReference1.Departamento[] getTbl_departamentos() {
            return base.Channel.getTbl_departamentos();
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Departamento[]> getTbl_departamentosAsync() {
            return base.Channel.getTbl_departamentosAsync();
        }
        
        public ASKI_VACACIONES.ServiceReference1.Jerarquia[] getTbl_jerarquia() {
            return base.Channel.getTbl_jerarquia();
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Jerarquia[]> getTbl_jerarquiaAsync() {
            return base.Channel.getTbl_jerarquiaAsync();
        }
        
        public ASKI_VACACIONES.ServiceReference1.Log_Vacaciones[] getTbl_log_vacaciones() {
            return base.Channel.getTbl_log_vacaciones();
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Log_Vacaciones[]> getTbl_log_vacacionesAsync() {
            return base.Channel.getTbl_log_vacacionesAsync();
        }
        
        public ASKI_VACACIONES.ServiceReference1.Permisos[] getTbl_permisos() {
            return base.Channel.getTbl_permisos();
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Permisos[]> getTbl_permisosAsync() {
            return base.Channel.getTbl_permisosAsync();
        }
        
        public ASKI_VACACIONES.ServiceReference1.Roles[] getTbl_roles() {
            return base.Channel.getTbl_roles();
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Roles[]> getTbl_rolesAsync() {
            return base.Channel.getTbl_rolesAsync();
        }
        
        public ASKI_VACACIONES.ServiceReference1.Status[] getTbl_status() {
            return base.Channel.getTbl_status();
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Status[]> getTbl_statusAsync() {
            return base.Channel.getTbl_statusAsync();
        }
        
        public ASKI_VACACIONES.ServiceReference1.Tipo_Dia[] getTbl_tipo_dia() {
            return base.Channel.getTbl_tipo_dia();
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Tipo_Dia[]> getTbl_tipo_diaAsync() {
            return base.Channel.getTbl_tipo_diaAsync();
        }
        
        public ASKI_VACACIONES.ServiceReference1.Usuario[] getTbl_usuarios() {
            return base.Channel.getTbl_usuarios();
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Usuario[]> getTbl_usuariosAsync() {
            return base.Channel.getTbl_usuariosAsync();
        }
        
        public ASKI_VACACIONES.ServiceReference1.Vacaciones[] getTbl_vacaciones() {
            return base.Channel.getTbl_vacaciones();
        }
        
        public System.Threading.Tasks.Task<ASKI_VACACIONES.ServiceReference1.Vacaciones[]> getTbl_vacacionesAsync() {
            return base.Channel.getTbl_vacacionesAsync();
        }
        
        public int getUltimoId_Roles() {
            return base.Channel.getUltimoId_Roles();
        }
        
        public System.Threading.Tasks.Task<int> getUltimoId_RolesAsync() {
            return base.Channel.getUltimoId_RolesAsync();
        }
        
        public string[] getLista_Permisos(int talento_humano) {
            return base.Channel.getLista_Permisos(talento_humano);
        }
        
        public System.Threading.Tasks.Task<string[]> getLista_PermisosAsync(int talento_humano) {
            return base.Channel.getLista_PermisosAsync(talento_humano);
        }
        
        public string[] getIdsRoles_Usuario(int talentoHumano) {
            return base.Channel.getIdsRoles_Usuario(talentoHumano);
        }
        
        public System.Threading.Tasks.Task<string[]> getIdsRoles_UsuarioAsync(int talentoHumano) {
            return base.Channel.getIdsRoles_UsuarioAsync(talentoHumano);
        }
        
        public string[] getIdDepartamentos_Usuario(int talentoHumano) {
            return base.Channel.getIdDepartamentos_Usuario(talentoHumano);
        }
        
        public System.Threading.Tasks.Task<string[]> getIdDepartamentos_UsuarioAsync(int talentoHumano) {
            return base.Channel.getIdDepartamentos_UsuarioAsync(talentoHumano);
        }
        
        public string[] get_fecha(int tipo_dia) {
            return base.Channel.get_fecha(tipo_dia);
        }
        
        public System.Threading.Tasks.Task<string[]> get_fechaAsync(int tipo_dia) {
            return base.Channel.get_fechaAsync(tipo_dia);
        }
        
        public int getultimoid_tipodia() {
            return base.Channel.getultimoid_tipodia();
        }
        
        public System.Threading.Tasks.Task<int> getultimoid_tipodiaAsync() {
            return base.Channel.getultimoid_tipodiaAsync();
        }
        
        public string[] get_eventos() {
            return base.Channel.get_eventos();
        }
        
        public System.Threading.Tasks.Task<string[]> get_eventosAsync() {
            return base.Channel.get_eventosAsync();
        }
        
        public string[] get_fecha_eventos(string evento) {
            return base.Channel.get_fecha_eventos(evento);
        }
        
        public System.Threading.Tasks.Task<string[]> get_fecha_eventosAsync(string evento) {
            return base.Channel.get_fecha_eventosAsync(evento);
        }
        
        public string[][] getDepartamento_Usuario() {
            return base.Channel.getDepartamento_Usuario();
        }
        
        public System.Threading.Tasks.Task<string[][]> getDepartamento_UsuarioAsync() {
            return base.Channel.getDepartamento_UsuarioAsync();
        }
        
        public string getJefe_Departamento(int departamentoid) {
            return base.Channel.getJefe_Departamento(departamentoid);
        }
        
        public System.Threading.Tasks.Task<string> getJefe_DepartamentoAsync(int departamentoid) {
            return base.Channel.getJefe_DepartamentoAsync(departamentoid);
        }
        
        public int getTalentoHumano_Jefe_Departamento(int departamentoid) {
            return base.Channel.getTalentoHumano_Jefe_Departamento(departamentoid);
        }
        
        public System.Threading.Tasks.Task<int> getTalentoHumano_Jefe_DepartamentoAsync(int departamentoid) {
            return base.Channel.getTalentoHumano_Jefe_DepartamentoAsync(departamentoid);
        }
        
        public int getTalentoHumano_Jefe(int talentoHumano_empleado, int departamentoid) {
            return base.Channel.getTalentoHumano_Jefe(talentoHumano_empleado, departamentoid);
        }
        
        public System.Threading.Tasks.Task<int> getTalentoHumano_JefeAsync(int talentoHumano_empleado, int departamentoid) {
            return base.Channel.getTalentoHumano_JefeAsync(talentoHumano_empleado, departamentoid);
        }
    }
}
